# Perfil ativo
# Para executar a aplicação localmente, o valor desta propriedade deve ser dev
# Para executar a aplicação em produção, o valor desta propriedade deve ser prd
spring:
  profiles:
    active: prd